# copy data set
BRFSS_c <- BRFSS_b

# recode heart attack variable
BRFSS_c$CVDINFR5 <- 9
BRFSS_c$CVDINFR5[BRFSS_c$CVDINFR4 == 1] <- 0
BRFSS_c$CVDINFR5[BRFSS_c$CVDINFR4 == 2] <- 1

table(BRFSS_c$CVDINFR4, BRFSS_c$CVDINFR5)

# recode teeth variable
BRFSS_c$RMVTETH5 <- 9
BRFSS_c$RMVTETH5[BRFSS_c$RMVTETH4 == 8] <- 0
BRFSS_c$RMVTETH5[BRFSS_c$RMVTETH4 == 1] <- 1
BRFSS_c$RMVTETH5[BRFSS_c$RMVTETH4 == 2] <- 2
BRFSS_c$RMVTETH5[BRFSS_c$RMVTETH4 == 3] <- 3

table(BRFSS_c$RMVTETH4, BRFSS_c$RMVTETH5)
