# recode age variable
BRFSS_c$AGEG5YR2 <- 9
BRFSS_c$AGEG5YR2[BRFSS_c$X_AGEG5YR > 6 &  BRFSS_c$X_AGEG5YR < 9] <- 0
BRFSS_c$AGEG5YR2[BRFSS_c$X_AGEG5YR > 8 &  BRFSS_c$X_AGEG5YR < 11] <- 1
BRFSS_c$AGEG5YR2[BRFSS_c$X_AGEG5YR > 10 &  BRFSS_c$X_AGEG5YR < 13] <- 2
BRFSS_c$AGEG5YR2[BRFSS_c$X_AGEG5YR == 13] <- 3

table(BRFSS_c$X_AGEG5YR, BRFSS_c$AGEG5YR2)

# make indicator variables
BRFSS_c$AGE1 <- 0
BRFSS_c$AGE2 <- 0
BRFSS_c$AGE3 <- 0
BRFSS_c$AGE4 <- 0

BRFSS_c$AGE1[BRFSS_c$AGEG5YR2 == 0] <- 1
BRFSS_c$AGE2[BRFSS_c$AGEG5YR2 == 1] <- 1
BRFSS_c$AGE3[BRFSS_c$AGEG5YR2 == 2] <- 1
BRFSS_c$AGE4[BRFSS_c$AGEG5YR2 == 3] <- 1

table(BRFSS_c$AGEG5YR2, BRFSS_c$AGE1)
table(BRFSS_c$AGEG5YR2, BRFSS_c$AGE2)
table(BRFSS_c$AGEG5YR2, BRFSS_c$AGE3)
table(BRFSS_c$AGEG5YR2, BRFSS_c$AGE4)

# Make education variable
BRFSS_c$EDGRP <- 9
BRFSS_c$EDGRP[BRFSS_c$EDUCA < 4] <- 0
BRFSS_c$EDGRP[BRFSS_c$EDUCA == 4] <- 1
BRFSS_c$EDGRP[BRFSS_c$EDUCA == 5] <- 2
BRFSS_c$EDGRP[BRFSS_c$EDUCA == 6] <- 3

table(BRFSS_b$EDUCA, BRFSS_c$EDGRP)

# make indicator variables
BRFSS_c$LOWED <- 0
BRFSS_c$HIGHSCHOOL <- 0
BRFSS_c$SOMECOLL <- 0
BRFSS_c$COLLEGE <- 0

BRFSS_c$LOWED[BRFSS_c$EDGRP == 0] <- 1
BRFSS_c$HIGHSCHOOL[BRFSS_c$EDGRP == 1] <- 1
BRFSS_c$SOMECOLL[BRFSS_c$EDGRP == 2] <- 1
BRFSS_c$COLLEGE[BRFSS_c$EDGRP == 3] <- 1

table(BRFSS_c$EDGRP, BRFSS_c$LOWED)
table(BRFSS_c$EDGRP, BRFSS_c$HIGHSCHOOL)
table(BRFSS_c$EDGRP, BRFSS_c$SOMECOLL)
table(BRFSS_c$EDGRP, BRFSS_c$COLLEGE)

# recode income variable
BRFSS_c$INCOME3 <- 9
BRFSS_c$INCOME3[BRFSS_c$INCOME2 < 3] <- 0
BRFSS_c$INCOME3[BRFSS_c$INCOME2 > 2 & BRFSS_c$INCOME2 < 5] <- 1
BRFSS_c$INCOME3[BRFSS_c$INCOME2 > 4 & BRFSS_c$INCOME2 < 6] <- 2
BRFSS_c$INCOME3[BRFSS_c$INCOME2 > 5 & BRFSS_c$INCOME2 < 7] <- 3
BRFSS_c$INCOME3[BRFSS_c$INCOME2 > 6 & BRFSS_c$INCOME2 < 9] <- 4

table(BRFSS_c$INCOME2, BRFSS_c$INCOME3)

# make indicator variables
BRFSS_c$INC1 <- 0
BRFSS_c$INC2 <- 0
BRFSS_c$INC3 <- 0
BRFSS_c$INC4 <- 0
BRFSS_c$INC5 <- 0

BRFSS_c$INC1[BRFSS_c$INCOME3 == 0] <- 1
BRFSS_c$INC2[BRFSS_c$INCOME3 == 1] <- 1
BRFSS_c$INC3[BRFSS_c$INCOME3 == 2] <- 1
BRFSS_c$INC4[BRFSS_c$INCOME3 == 3] <- 1
BRFSS_c$INC5[BRFSS_c$INCOME3 == 4] <- 1

table(BRFSS_c$INCOME3, BRFSS_c$INC1)
table(BRFSS_c$INCOME3, BRFSS_c$INC2)
table(BRFSS_c$INCOME3, BRFSS_c$INC3)
table(BRFSS_c$INCOME3, BRFSS_c$INC4)
table(BRFSS_c$INCOME3, BRFSS_c$INC5)

