# look at the data set
str(BRFSS_e)

head(BRFSS_e)
tail(BRFSS_e)

# Make a copy of the dataset
BRFSS_f <- BRFSS_e

# make sex variables
BRFSS_f$SEX <- 9
BRFSS_f$SEX[BRFSS_f$SEX1 == 1] <- 1
BRFSS_f$SEX[BRFSS_f$SEX1 == 2] <- 2

table(BRFSS_f$SEX)

BRFSS_g <- subset(BRFSS_b, )

BRFSS_f$MALE <- 0
BRFSS_f$MALE[BRFSS_f$SEX == 1] <- 1

table(BRFSS_f$MALE, BRFSS_f$SEX)

# make Hispanic variable
BRFSS_f$HISPANIC <- 0
BRFSS_f$HISPANIC[BRFSS_f$X_HISPANC == 1] <- 1

table(BRFSS_f$HISPANIC, BRFSS_f$X_HISPANC)

# make race variables
BRFSS_f$RACEGRP <- 9
BRFSS_f$RACEGRP[BRFSS_f$X_MRACE1 == 1] <- 1
BRFSS_f$RACEGRP[BRFSS_f$X_MRACE1 == 2] <- 2
BRFSS_f$RACEGRP[BRFSS_f$X_MRACE1 == 3] <- 3
BRFSS_f$RACEGRP[BRFSS_f$X_MRACE1 == 4] <- 4
BRFSS_f$RACEGRP[BRFSS_f$X_MRACE1 == 5] <- 5
BRFSS_f$RACEGRP[BRFSS_f$X_MRACE1 == 6 | BRFSS_f$X_MRACE1 == 7] <- 6

table(BRFSS_f$RACEGRP , BRFSS_f$X_MRACE1)

BRFSS_f$BLACK <- 0
BRFSS_f$ASIAN <- 0
BRFSS_f$OTHRACE <- 0

BRFSS_f$BLACK[BRFSS_f$RACEGRP == 2] <- 1
table(BRFSS_f$RACEGRP, BRFSS_f$BLACK)

BRFSS_f$ASIAN[BRFSS_f$RACEGRP == 4] <- 1
table(BRFSS_f$RACEGRP, BRFSS_f$ASIAN)

BRFSS_f$OTHRACE[BRFSS_f$RACEGRP == 3 | BRFSS_f$RACEGRP == 5 | BRFSS_f$RACEGRP == 6 | BRFSS_f$RACEGRP == 7] <- 1
table(BRFSS_f$RACEGRP, BRFSS_f$OTHRACE)

# make age variables
BRFSS_f$AGE[BRFSS_f$X_AGEG5YR < 9] <- 1
BRFSS_f$AGE[BRFSS_f$X_AGEG5YR > 8 & BRFSS_f$X_AGEG5YR < 11] <- 2
BRFSS_f$AGE[BRFSS_f$X_AGEG5YR > 10] <- 3

table(BRFSS_f$X_AGEG5YR, BRFSS_f$AGE)

BRFSS_f$AGE1 <- 0
BRFSS_f$AGE2 <- 0
BRFSS_f$AGE3 <- 0

BRFSS_f$AGE1[BRFSS_f$AGE == 1] <- 1
table(BRFSS_f$AGE, BRFSS_f$AGE1)

BRFSS_f$AGE2[BRFSS_f$AGE == 2] <- 1
table(BRFSS_f$AGE, BRFSS_f$AGE2)

BRFSS_f$AGE3[BRFSS_f$AGE == 3] <- 1
table(BRFSS_f$AGE, BRFSS_f$AGE3)

# make the education variables
BRFSS_f$EDGRP <- 9
BRFSS_f$EDGRP[BRFSS_f$EDUCA < 4] <- 1
BRFSS_f$EDGRP[BRFSS_f$EDUCA == 4] <- 2
BRFSS_f$EDGRP[BRFSS_f$EDUCA == 5] <- 3
BRFSS_f$EDGRP[BRFSS_f$EDUCA == 6] <- 4

table(BRFSS_f$EDUCA, BRFSS_f$EDGRP)

BRFSS_f$LOWED <- 0
BRFSS_f$HIGHSCOOL <- 0
BRFSS_f$SOMECOL <- 0
BRFSS_f$COLLEGE <- 0

BRFSS_f$LOWED[BRFSS_f$EDGRP == 1] <- 1
BRFSS_f$HIGHSCOOL[BRFSS_f$EDGR == 2] <- 1
BRFSS_f$SOMECOL[BRFSS_f$EDGR == 3] <- 1
BRFSS_f$COLLEGE[BRFSS_f$EDGR == 4] <- 1

table(BRFSS_f$EDGRP, BRFSS_f$LOWED)
table(BRFSS_f$EDGRP, BRFSS_f$HIGHSCOOL)
table(BRFSS_f$EDGRP, BRFSS_f$SOMECOL)
table(BRFSS_f$EDGRP, BRFSS_f$COLLEGE)

# make the income variables
BRFSS_f$INCOME3 <- 9
BRFSS_f$INCOME3[BRFSS_f$INCOME2 < 3] <- 1
BRFSS_f$INCOME3[BRFSS_f$INCOME2 > 2 &  BRFSS_f$INCOME2 < 5] <- 2
BRFSS_f$INCOME3[BRFSS_f$INCOME2 > 4 &  BRFSS_f$INCOME2 < 6] <- 3
BRFSS_f$INCOME3[BRFSS_f$INCOME2 == 6] <- 4
BRFSS_f$INCOME3[BRFSS_f$INCOME2 > 6 &  BRFSS_f$INCOME2 < 9] <- 5

table(BRFSS_f$INCOME2, BRFSS_f$INCOME3)

BRFSS_f$INC1 <- 0
BRFSS_f$INC2 <- 0
BRFSS_f$INC3 <- 0
BRFSS_f$INC4 <- 0

BRFSS_f$INC1[BRFSS_f$INCOME3 == 1] <- 1
BRFSS_f$INC2[BRFSS_f$INCOME3 == 2] <- 1
BRFSS_f$INC3[BRFSS_f$INCOME3 == 3] <- 1
BRFSS_f$INC4[BRFSS_f$INCOME3 == 4] <- 1
BRFSS_f$INC5[BRFSS_f$INCOME3 == 5] <- 1

table(BRFSS_f$INCOME3, BRFSS_f$INC1)
table(BRFSS_f$INCOME3, BRFSS_f$INC2)
table(BRFSS_f$INCOME3, BRFSS_f$INC3)
table(BRFSS_f$INCOME3, BRFSS_f$INC4)
table(BRFSS_f$INCOME3, BRFSS_f$INC5)

# make the dental visit variables
BRFSS_f$DENVST[BRFSS_f$X_DENVST3 == 1] <- 1
BRFSS_f$NODENVST[BRFSS_f$X_DENVST3 == 2] <- 1

table(BRFSS_f$X_DENVST3, BRFSS_f$DENVST)
table(BRFSS_f$X_DENVST3, BRFSS_f$NODENVST)

# make the smoker variables
BRFSS_f$SMK <- 9
BRFSS_f$SMK[BRFSS_f$X_SMOKER3 < 3] <- 3
BRFSS_f$SMK[BRFSS_f$X_SMOKER3 == 3] <- 2
BRFSS_f$SMK[BRFSS_f$X_SMOKER3 == 4] <- 1

table(BRFSS_f$X_SMOKER3, BRFSS_f$SMK)

BRFSS_f$NEVERSMK <- 0
BRFSS_f$FRMRSMK <- 0
BRFSS_f$SMOKE <- 0


BRFSS_f$NEVERSMK[BRFSS_f$SMK == 1] <- 1
BRFSS_f$FRMRSMK[BRFSS_f$SMK == 2] <- 1
BRFSS_f$SMOKE[BRFSS_f$SMK == 3] <- 1

# make the diabetes variables
BRFSS_f$DIABETE4 <- 9
BRFSS_f$DIABETE4[BRFSS_f$DIABETE3 == 1] <- 1
BRFSS_f$DIABETE4[BRFSS_f$DIABETE3 > 1 & BRFSS_f$DIABETE3 < 5] <- 2

table(BRFSS_f$DIABETE3, BRFSS_f$DIABETE4)

BRFSS_f$HASDIABETES <- 0
BRFSS_f$NODIABETES <- 0

BRFSS_f$HASDIABETES[BRFSS_f$DIABETE4 == 1] <- 1
BRFSS_f$NODIABETES[BRFSS_f$DIABETE4 == 2] <- 1

table(BRFSS_f$DIABETE4, BRFSS_f$HASDIABETES)
table(BRFSS_f$DIABETE4, BRFSS_f$NODIABETES)

# make PA variables
BRFSS_f$PA<- 9
BRFSS_f$PA[BRFSS_f$EXERANY2 ==1] <- 1
BRFSS_f$PA[BRFSS_f$EXERANY2 ==2] <- 2

table(BRFSS_f$PA, BRFSS_f$EXERANY2)

BRFSS_f$NOEXER <- 0
BRFSS_f$NOEXER[BRFSS_f$PA ==2] <- 1
table(BRFSS_f$NOEXER, BRFSS_f$PA)

# Make BMI variables
BRFSS_f$BMICAT<- 9
BRFSS_f$BMICAT[BRFSS_f$X_BMI5CAT ==1] <- 1
BRFSS_f$BMICAT[BRFSS_f$X_BMI5CAT ==2] <- 2
BRFSS_f$BMICAT[BRFSS_f$X_BMI5CAT ==3] <- 3
BRFSS_f$BMICAT[BRFSS_f$X_BMI5CAT ==4] <- 4

table(BRFSS_f$BMICAT, BRFSS_f$X_BMI5CAT)

BRFSS_f$UNDWT <- 0
BRFSS_f$OVWT <- 0
BRFSS_f$OBESE <- 0

BRFSS_f$UNDWT[BRFSS_f$BMICAT== 1] <- 1
table(BRFSS_f$UNDWT, BRFSS_f$BMICAT)

BRFSS_f$OVWT[BRFSS_f$BMICAT== 3] <- 1
table(BRFSS_f$OVWT, BRFSS_f$BMICAT)

BRFSS_f$OBESE[BRFSS_f$BMICAT== 4] <- 1
table(BRFSS_f$OBESE, BRFSS_f$BMICAT)

# look at the data set
str(BRFSS_f)

head(BRFSS_f)
tail(BRFSS_f)
