---
title: "Revisiting the Cross-Sectional Association Between Missing Teeth and Cardiovascular Disease: BRFSS 2018"
author: "Paul G. Smith"
date: '`r paste("First created on Nov 7, 2019. Updated on", format(Sys.Date(),"%b %d, %Y"))`'
output: 
  github_document:
    toc: true
    html_preview: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The relationship between oral health and cardiovascular disease has been an important area of research in the last decade. The objective of the current study is to perform an analysis of BRFSS 2018 data based on the previously published work of R. Constance Wiener and Usha Sambamoorthi from 2010. **This analysis is meant to be an example of the data analysis and R programming techniques required to perform both a descriptive and regression analysis of publically available data.**

In their orignal 2010 analysis, Weiner and Sambamoorth evaluated the association of cardiovascular disease and the number of missing teeth as a risk indicator. In this analysis, the 2018 BRFSS data and initial variables from that study will be used as the basis for demonstrating the products and coding required for (1) an descriptive analysis and (2) a regression analysis using R.

For more information about the original study check out the published article at:
https://www.ncbi.nlm.nih.gov/pubmed/24624297

